name: predict_pv_yield
channels:
  - pytorch
  - pvlib
  - conda-forge
dependencies:
  - python>=3.8
  
  # Scientific Python
  - numpy
  - pandas
  - matplotlib
  - zarr
  - xarray
  - ipykernel
  
  # Cloud & distributed compute
  - google-cloud-storage
  - gcsfs
  - dask
  - python-graphviz  # used for visualising dask graphs
  
  # Images
  - conda-forge::opencv  # also run `apt install libgl1-mesa-glx`
  - scikit-image
  
  # Machine learning
  - pytorch::pytorch  # explicitly specify pytorch channel to prevent conda from using conda-forge for pytorch, and hence installing the CPU-only version.
  - cudatoolkit=11.0
  - pytorch::torchvision
  - pytorch-lightning

  # PV & Geospatial
  - pvlib
  - pyproj

  # Organizing experiments
  - conda-forge::neptune-client